address comment

diff --git a/.git-hooks/pre-push b/.git-hooks/pre-push
--- a/.git-hooks/pre-push
+++ b/.git-hooks/pre-push
@@ -11,15 +11,14 @@ echo "[goling]"
 go list straas.io/... | grep -v "mocks" | xargs -n 1 golint
 
 echo
-#go test $(go list straas.io/...)
-go
+go test $(go list straas.io/...)
 
 if [ $? -ne 0 ]; then
-	echo "Run unit test fail, push anyway (y/N) ?"
-	read -n 1 -r
+  echo "Run unit test fail, push anyway (y/N) ?"
+  read -n 1 -r
 
-	if [[ $REPLY == ^[Yy]$ ]]; then
-	    exit 0
-	fi
-	exit 1
+  if [[ $REPLY =~ ^[Yy]$ ]]; then
+    exit 0
+  fi
+  exit 1
 fi
